# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

env:
  REGISTRY: 'europe-docker.pkg.dev'

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIP }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
          access_token_lifetime: '600s' # 10 minutes should be long enough
          create_credentials_file: false
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'adopt'
          java-version-file: '.tool-versions'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: 'docker/login-action@v3'
        with:
          registry: ${{ env.REGISTRY }}
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.welcome=never jib
